name: EasyChat
version: '${project.version}'
main: ru.sliva.easychat.EasyChat
api-version: 1.13
load: STARTUP
depend: [LuckPerms]
authors: [ sliva_ru ]
description: Eazy chat for servers.
website: https://github.com/Geo3gamer/EzChat
commands:
  ezchat:
    description: 'Reloads configuration'
    permission: 'easychat.ezchat'
    usage: '/easychat'
permissions:
  easychat.color:
    description: 'Colors the chat message'
    default: 'op'
  easychat.ezchat:
    description: 'Give access to reload command'
    default: 'op'
